name: flutter_lab
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  fluttertoast: ^8.2.4
  smooth_page_indicator: ^1.1.0
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  http: ^1.2.1
  dio: ^5.4.1
  rxdart: ^0.27.7
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # 개발자의 임의 폴더.. 리소스 폴더를 등록..
  # 기본은 파일단위 등록인데.. 만약 특정 폴더의 모든 파일을 등록하려면 폴더명 뒤에 / 추가..
  # 등록한 폴더만, 서브 폴더는 등록안된다..
  assets:
    - images/
    - assets/icon/
    - assets/text/
